// داده محصولات کوچه ادویه
// هر محصول: id, name, category (spice|nuts), catLabel, icon, desc, longDesc, packages[]
const PRODUCTS = [
  // ---------- ادویه‌جات (10) ----------
  { id:"saffron", name:"زعفران سرگل", category:"spice", catLabel:"ادویه‌جات", icon:"🌸",
    desc:"زعفران درجه یک، رشته کامل و پرعطر.",
    longDesc:"زعفران سرگل از بهترین مزارع خراسان، خشک‌شده به روش سنتی برای حفظ حداکثر عطر و رنگ‌دهی. مناسب پلو، دسر و دمنوش.",
    packages:[{size:"۱۰۰ گرم",price:1850000},{size:"۲۵۰ گرم",price:4400000},{size:"۵۰۰ گرم",price:8600000},{size:"۱ کیلوگرم",price:16800000}]},
  { id:"cinnamon", name:"دارچین چوبی", category:"spice", catLabel:"ادویه‌جات", icon:"🪵",
    desc:"دارچین درجه یک، پودر و چوب.",
    longDesc:"دارچین با رایحه گرم و شیرین، مناسب برای شیرینی‌پزی، چای و غذاهای خورشتی.",
    packages:[{size:"۱۰۰ گرم",price:95000},{size:"۲۵۰ گرم",price:220000},{size:"۵۰۰ گرم",price:410000},{size:"۱ کیلوگرم",price:780000}]},
  { id:"cumin", name:"زیره سبز", category:"spice", catLabel:"ادویه‌جات", icon:"🌿",
    desc:"زیره سبز معطر و تازه آسیاب.",
    longDesc:"زیره سبز از محصولات ادویه‌ای پرمصرف آشپزخانه ایرانی، مناسب برای پلو، خورشت و دورچین.",
    packages:[{size:"۱۰۰ گرم",price:78000},{size:"۲۵۰ گرم",price:180000},{size:"۵۰۰ گرم",price:340000},{size:"۱ کیلوگرم",price:650000}]},
  { id:"black-pepper", name:"فلفل سیاه دانه", category:"spice", catLabel:"ادویه‌جات", icon:"⚫",
    desc:"فلفل سیاه تند و معطر.",
    longDesc:"فلفل سیاه دانه‌درشت، مناسب برای آسیاب تازه روی غذا، تندی متعادل و رایحه قوی.",
    packages:[{size:"۱۰۰ گرم",price:110000},{size:"۲۵۰ گرم",price:255000},{size:"۵۰۰ گرم",price:480000},{size:"۱ کیلوگرم",price:920000}]},
  { id:"turmeric", name:"زردچوبه", category:"spice", catLabel:"ادویه‌جات", icon:"🟡",
    desc:"زردچوبه خالص و پررنگ.",
    longDesc:"زردچوبه اصل، بدون افزودنی، رنگ‌دهی قوی برای انواع خورشت و برنج.",
    packages:[{size:"۱۰۰ گرم",price:65000},{size:"۲۵۰ گرم",price:150000},{size:"۵۰۰ گرم",price:280000},{size:"۱ کیلوگرم",price:540000}]},
  { id:"cardamom", name:"هل سبز", category:"spice", catLabel:"ادویه‌جات", icon:"💚",
    desc:"هل سبز درجه یک برای چای و شیرینی.",
    longDesc:"هل سبز با رایحه خنک و لطیف، پرمصرف در چای، قهوه و شیرینی‌جات سنتی.",
    packages:[{size:"۱۰۰ گرم",price:480000},{size:"۲۵۰ گرم",price:1150000},{size:"۵۰۰ گرم",price:2200000},{size:"۱ کیلوگرم",price:4300000}]},
  { id:"sumac", name:"سماق ناب", category:"spice", catLabel:"ادویه‌جات", icon:"🔴",
    desc:"سماق ترش و تازه آسیاب.",
    longDesc:"سماق طبیعی بدون نمک افزوده، مناسب سالاد، کباب و خورش.",
    packages:[{size:"۱۰۰ گرم",price:58000},{size:"۲۵۰ گرم",price:135000},{size:"۵۰۰ گرم",price:250000},{size:"۱ کیلوگرم",price:480000}]},
  { id:"paprika", name:"پاپریکا شیرین", category:"spice", catLabel:"ادویه‌جات", icon:"🌶️",
    desc:"پاپریکا خوش‌رنگ و ملایم.",
    longDesc:"پاپریکا شیرین با رنگ قرمز زنده، مناسب سس، غذاهای کبابی و تزیین.",
    packages:[{size:"۱۰۰ گرم",price:70000},{size:"۲۵۰ گرم",price:160000},{size:"۵۰۰ گرم",price:300000},{size:"۱ کیلوگرم",price:580000}]},
  { id:"coriander", name:"پودر گشنیز", category:"spice", catLabel:"ادویه‌جات", icon:"🌱",
    desc:"گشنیز خشک و تازه آسیاب‌شده.",
    longDesc:"پودر گشنیز معطر، جزو پایه‌ای‌ترین ادویه‌های آشپزخانه ایرانی و مدیترانه‌ای.",
    packages:[{size:"۱۰۰ گرم",price:60000},{size:"۲۵۰ گرم",price:140000},{size:"۵۰۰ گرم",price:265000},{size:"۱ کیلوگرم",price:510000}]},
  { id:"nutmeg", name:"جوز هندی", category:"spice", catLabel:"ادویه‌جات", icon:"🟤",
    desc:"جوز هندی معطر و تند.",
    longDesc:"جوز هندی، ادویه‌ای گرم و معطر برای شیرینی، سس‌های خامه‌ای و خورش.",
    packages:[{size:"۱۰۰ گرم",price:150000},{size:"۲۵۰ گرم",price:350000},{size:"۵۰۰ گرم",price:660000},{size:"۱ کیلوگرم",price:1280000}]},

  // ---------- خشکبار (10) ----------
  { id:"pistachio", name:"پسته اکبری", category:"nuts", catLabel:"خشکبار", icon:"🥜",
    desc:"پسته اکبری درشت و تازه.",
    longDesc:"پسته اکبری از باغات کرمان، مغز پر و طعم اصیل، مناسب پذیرایی و شیرینی‌پزی.",
    packages:[{size:"۱۰۰ گرم",price:210000},{size:"۲۵۰ گرم",price:500000},{size:"۵۰۰ گرم",price:960000},{size:"۱ کیلوگرم",price:1880000}]},
  { id:"almond", name:"بادام درختی", category:"nuts", catLabel:"خشکبار", icon:"🌰",
    desc:"بادام تازه و خام.",
    longDesc:"بادام درختی خام و تازه، منبع خوب پروتئین و چربی سالم، مناسب مصرف روزانه.",
    packages:[{size:"۱۰۰ گرم",price:135000},{size:"۲۵۰ گرم",price:320000},{size:"۵۰۰ گرم",price:610000},{size:"۱ کیلوگرم",price:1180000}]},
  { id:"walnut", name:"گردو مغز کامل", category:"nuts", catLabel:"خشکبار", icon:"🥧",
    desc:"گردوی تازه، مغز کامل و روشن.",
    longDesc:"گردوی مغز کامل، تازه و بدون تلخی، مناسب مصرف مستقیم و آشپزی.",
    packages:[{size:"۱۰۰ گرم",price:120000},{size:"۲۵۰ گرم",price:280000},{size:"۵۰۰ گرم",price:540000},{size:"۱ کیلوگرم",price:1040000}]},
  { id:"raisin", name:"کشمش پلویی", category:"nuts", catLabel:"خشکبار", icon:"🍇",
    desc:"کشمش طلایی و شیرین.",
    longDesc:"کشمش پلویی مخصوص، دانه‌درشت و شیرین، مناسب پلو و شیرینی.",
    packages:[{size:"۱۰۰ گرم",price:45000},{size:"۲۵۰ گرم",price:105000},{size:"۵۰۰ گرم",price:195000},{size:"۱ کیلوگرم",price:370000}]},
  { id:"dried-mulberry", name:"توت خشک", category:"nuts", catLabel:"خشکبار", icon:"🫐",
    desc:"توت خشک سفید، طبیعی و شیرین.",
    longDesc:"توت خشک سفید بدون شکر افزوده، میان‌وعده‌ای سالم و پرانرژی.",
    packages:[{size:"۱۰۰ گرم",price:58000},{size:"۲۵۰ گرم",price:135000},{size:"۵۰۰ گرم",price:255000},{size:"۱ کیلوگرم",price:490000}]},
  { id:"date", name:"خرمای مضافتی", category:"nuts", catLabel:"خشکبار", icon:"🌴",
    desc:"خرمای مضافتی نرم و شیرین.",
    longDesc:"خرمای مضافتی بم، نرم و پرگوشت، سرشار از انرژی طبیعی.",
    packages:[{size:"۱۰۰ گرم",price:38000},{size:"۲۵۰ گرم",price:88000},{size:"۵۰۰ گرم",price:165000},{size:"۱ کیلوگرم",price:310000}]},
  { id:"barberry", name:"زرشک پفکی", category:"nuts", catLabel:"خشکبار", icon:"🔺",
    desc:"زرشک ترش و تازه.",
    longDesc:"زرشک پفکی بدون هسته، دانه‌ریز و ترش، مخصوص زرشک‌پلو.",
    packages:[{size:"۱۰۰ گرم",price:65000},{size:"۲۵۰ گرم",price:150000},{size:"۵۰۰ گرم",price:285000},{size:"۱ کیلوگرم",price:550000}]},
  { id:"hazelnut", name:"فندق خام", category:"nuts", catLabel:"خشکبار", icon:"🌰",
    desc:"فندق تازه و روغنی.",
    longDesc:"فندق خام و تازه، طعم ملایم و روغنی، مناسب مصرف مستقیم و شیرینی‌پزی.",
    packages:[{size:"۱۰۰ گرم",price:145000},{size:"۲۵۰ گرم",price:340000},{size:"۵۰۰ گرم",price:650000},{size:"۱ کیلوگرم",price:1260000}]},
  { id:"dried-fig", name:"انجیر خشک", category:"nuts", catLabel:"خشکبار", icon:"🟣",
    desc:"انجیر خشک استهبان، نرم و شیرین.",
    longDesc:"انجیر خشک استهبان، خشک‌شده به روش طبیعی زیر آفتاب، سرشار از فیبر.",
    packages:[{size:"۱۰۰ گرم",price:80000},{size:"۲۵۰ گرم",price:185000},{size:"۵۰۰ گرم",price:350000},{size:"۱ کیلوگرم",price:670000}]},
  { id:"mixed-nuts", name:"آجیل مخلوط شور", category:"nuts", catLabel:"خشکبار", icon:"🥨",
    desc:"ترکیب مغزهای برشته و شور.",
    longDesc:"آجیل مخلوط شامل بادام، پسته، فندق و تخمه، برشته و شور، مناسب پذیرایی.",
    packages:[{size:"۱۰۰ گرم",price:115000},{size:"۲۵۰ گرم",price:270000},{size:"۵۰۰ گرم",price:520000},{size:"۱ کیلوگرم",price:1010000}]},
];

function formatToman(n){
  return n.toLocaleString('fa-IR') + ' تومان';
}
